export declare const APOLLO_OFFLINE_QUEUE = "APOLLO_OFFLINE_QUEUE";
export declare const APOLLO_OFFLINE_COMMIT = "APOLLO_OFFLINE_COMMIT";
export declare const APOLLO_OFFLINE_ROLLBACK = "APOLLO_OFFLINE_ROLLBACK";
export declare const REHYDRATE_STORE = "REHYDRATE_STORE";
